export type HelpAudience = "all" | "operator" | "admin";
export type HelpMenuGroup = "Operaciones" | "Productos" | "Administrativo";

export type HelpAction = {
  id: string;
  title: string;
  screenArea: string;
  audience: HelpAudience;
  note?: string;
  steps: string[];
};

export type HelpSection = {
  id: string;
  menuGroup: HelpMenuGroup;
  menuButton: string;
  screenTitle: string;
  route: string;
  access: HelpAudience;
  summary: string;
  screenAreas: string[];
  actions: HelpAction[];
};

export const helpSections: HelpSection[] = [
  {
    id: "sales",
    menuGroup: "Operaciones",
    menuButton: "Ventas",
    screenTitle: "Pantalla de Ventas",
    route: "/sales",
    access: "all",
    summary: "Sirve para buscar productos, armar el carrito, cobrar y sacar el recibo.",
    screenAreas: ["Buscador de productos", "Carrito", "Pago de compra", "Resumen de venta"],
    actions: [
      {
        id: "sales-add-products",
        title: "Buscar y agregar productos a la venta",
        screenArea: "Buscador de productos",
        audience: "all",
        steps: [
          "Entra en Ventas desde el menu principal.",
          "Busca el producto por nombre, codigo de barras, categoria o precio.",
          "Selecciona el producto correcto en la lista.",
          "Revisa la cantidad y pulsa Agregar producto.",
          "Confirma que el producto aparezca en el carrito.",
        ],
      },
      {
        id: "sales-adjust-cart",
        title: "Cambiar cantidades o quitar productos del carrito",
        screenArea: "Carrito",
        audience: "all",
        steps: [
          "Mira el bloque del carrito antes de cobrar.",
          "Si falta una unidad, usa el boton para sumar.",
          "Si sobra una unidad, usa el boton para restar.",
          "Si un producto no debe ir, dejalo en cero o quitalo desde el mismo carrito.",
          "Cuando el carrito quede correcto, pasa al pago.",
        ],
      },
      {
        id: "sales-charge",
        title: "Cobrar una venta",
        screenArea: "Pago de compra",
        audience: "all",
        note: "Si la caja esta cerrada, primero debes abrirla desde el boton Caja.",
        steps: [
          "Con el carrito listo, crea la orden para pasar al pago.",
          "En la ventana de pago, elige el metodo de cobro.",
          "Revisa el total final, porque puede cambiar por descuentos o recargos.",
          "Pulsa Aprobar pago y espera la confirmacion.",
          "Cuando termine, el sistema te llevara al resumen de la venta.",
        ],
      },
      {
        id: "sales-receipt",
        title: "Imprimir el recibo de la venta",
        screenArea: "Resumen de venta",
        audience: "all",
        steps: [
          "Al terminar el cobro, entra o permanece en la pantalla Resumen.",
          "Revisa orden, fecha, metodo de pago y total.",
          "Pulsa Quiere imprimir recibo.",
          "Si el navegador abre una ventana, permite la impresion.",
          "Despues puedes volver a Ventas o regresar al menu principal.",
        ],
      },
    ],
  },
  {
    id: "cash",
    menuGroup: "Operaciones",
    menuButton: "Caja",
    screenTitle: "Pantalla de Caja",
    route: "/cash",
    access: "all",
    summary: "Se usa para abrir caja, pedir el cierre y, si eres administrador, revisar cierres pendientes.",
    screenAreas: ["Caja", "Cierre de caja", "Asignaciones", "Revision administrativa"],
    actions: [
      {
        id: "cash-open",
        title: "Abrir caja al comenzar el turno",
        screenArea: "Caja",
        audience: "all",
        steps: [
          "Entra en Caja al iniciar tu jornada.",
          "Si tienes un monto asignado, revisalo antes de escribir nada. Si eres administrador, puedes abrir con el monto real aunque no tengas asignacion.",
          "Escribe el efectivo real que recibiste para abrir.",
          "Pulsa Abrir caja.",
          "Confirma que el estado cambie a Caja abierta antes de vender.",
        ],
      },
      {
        id: "cash-request-close",
        title: "Solicitar cierre de caja al terminar",
        screenArea: "Caja",
        audience: "all",
        steps: [
          "Cuando termines tu turno, entra de nuevo en Caja.",
          "Revisa ventas, gastos y datos del turno.",
          "Escribe el efectivo que realmente quedo en caja.",
          "Pulsa Solicitar cierre.",
          "Espera la revision del administrador si tu perfil trabaja con control administrativo.",
        ],
      },
      {
        id: "cash-assign-opening",
        title: "Asignar monto de apertura a un usuario",
        screenArea: "Asignaciones",
        audience: "admin",
        steps: [
          "Entra en Caja con perfil administrador.",
          "Busca la tarjeta o fila del usuario al que vas a asignar apertura.",
          "Elige el turno correcto y escribe el monto a entregar.",
          "Pulsa Guardar.",
          "Pide al operador que abra caja usando ese monto. Si cubres un turno, puedes abrir tu propia caja sin asignacion.",
        ],
      },
      {
        id: "cash-review-close",
        title: "Revisar y confirmar un cierre pendiente",
        screenArea: "Cierre de caja",
        audience: "admin",
        note: "Aqui conviene revisar con calma porque afecta el cierre contable del turno.",
        steps: [
          "Entra en la pestana Cierre de caja.",
          "Selecciona una jornada pendiente de cierre.",
          "Compara apertura, ventas en efectivo, gastos, vuelto de mercancia y cierre declarado.",
          "Marca los controles como correctos o deja notas si ves diferencias.",
          "Pulsa Confirmar cierre cuando todo coincida o cuando la observacion ya este documentada.",
        ],
      },
    ],
  },
  {
    id: "requests",
    menuGroup: "Operaciones",
    menuButton: "Solicitudes",
    screenTitle: "Pantalla de Solicitudes",
    route: "/requests",
    access: "all",
    summary: "Permite pedir mercancia o permisos y seguir el estado de cada solicitud.",
    screenAreas: ["Formulario", "Listado", "Estado de solicitud"],
    actions: [
      {
        id: "requests-create",
        title: "Crear una solicitud nueva",
        screenArea: "Formulario",
        audience: "all",
        steps: [
          "Entra en Solicitudes.",
          "Elige si la solicitud es de mercancia o de permisos.",
          "Escribe la descripcion de forma clara y corta.",
          "Pulsa el boton para enviar la solicitud.",
          "Revisa en el listado que haya quedado como Pendiente.",
        ],
      },
      {
        id: "requests-edit",
        title: "Modificar una solicitud pendiente",
        screenArea: "Listado",
        audience: "all",
        steps: [
          "Busca tu solicitud pendiente en el listado.",
          "Selecciona la solicitud para cargarla otra vez en el formulario.",
          "Corrige tipo o descripcion.",
          "Guarda la actualizacion.",
          "Verifica que siga pendiente con la informacion correcta.",
        ],
      },
      {
        id: "requests-cancel",
        title: "Cancelar una solicitud pendiente",
        screenArea: "Listado",
        audience: "all",
        steps: [
          "Ubica la solicitud pendiente que ya no necesitas.",
          "Abre la opcion de cancelacion.",
          "Confirma la cancelacion en la ventana que aparece.",
          "Comprueba que la solicitud salga del flujo pendiente o cambie de estado.",
        ],
      },
      {
        id: "requests-status",
        title: "Revisar si una solicitud fue aprobada o rechazada",
        screenArea: "Estado de solicitud",
        audience: "all",
        steps: [
          "Entra en Solicitudes cuando quieras revisar una respuesta.",
          "Usa el filtro por estado si tienes muchas solicitudes.",
          "Lee el estado mostrado: Pendiente, Aprobado o Rechazado.",
          "Si la solicitud fue revisada, revisa tambien el comentario del administrador.",
        ],
      },
    ],
  },
  {
    id: "feedback",
    menuGroup: "Operaciones",
    menuButton: "Sugerencias y reclamos",
    screenTitle: "Pantalla de Sugerencias y Reclamos",
    route: "/feedback",
    access: "all",
    summary: "Sirve para dejar comentarios operativos. El administrador tambien puede ver el libro completo.",
    screenAreas: ["Registrar comentario", "Listado administrativo"],
    actions: [
      {
        id: "feedback-create",
        title: "Registrar una sugerencia o un reclamo",
        screenArea: "Registrar comentario",
        audience: "all",
        steps: [
          "Entra en Sugerencias y reclamos.",
          "Elige si tu comentario es sugerencia o reclamo.",
          "Escribe el mensaje con lenguaje simple y concreto.",
          "Si quieres, marca la opcion anonima.",
          "Pulsa el boton para registrar la entrada.",
        ],
      },
      {
        id: "feedback-anonymous",
        title: "Enviar el comentario como anonimo",
        screenArea: "Registrar comentario",
        audience: "all",
        steps: [
          "Completa el comentario normalmente.",
          "Marca la casilla Enviar como anonimo.",
          "Revisa la nota que explica que el nombre no se vera en el listado.",
          "Guarda la entrada.",
        ],
      },
      {
        id: "feedback-list",
        title: "Revisar el libro completo",
        screenArea: "Listado administrativo",
        audience: "admin",
        steps: [
          "Entra con perfil administrador.",
          "Abre la pestana Listado.",
          "Usa el buscador o el filtro por tipo si necesitas encontrar una entrada.",
          "Lee fecha, autor visible, tipo y mensaje.",
          "Usa esta vista para seguimiento interno, no para editar respuestas.",
        ],
      },
    ],
  },
  {
    id: "confirm-expense",
    menuGroup: "Operaciones",
    menuButton: "Confirmar Gasto",
    screenTitle: "Pantalla de Gastos enfocada en confirmacion",
    route: "/expenses",
    access: "all",
    summary: "Este acceso lleva directo a la parte de confirmacion de gastos y al historial.",
    screenAreas: ["Confirmar Gasto", "Historial"],
    actions: [
      {
        id: "confirm-expense-normal",
        title: "Confirmar un gasto con el mismo monto asignado",
        screenArea: "Confirmar Gasto",
        audience: "all",
        steps: [
          "Entra en Confirmar Gasto.",
          "Selecciona un gasto pendiente de la lista.",
          "Deja la opcion Usar monto asignado.",
          "Revisa la imagen o la informacion cargada.",
          "Pulsa Confirmar Gasto.",
        ],
      },
      {
        id: "confirm-expense-different",
        title: "Confirmar un gasto con monto diferente",
        screenArea: "Confirmar Gasto",
        audience: "all",
        note: "Cuando el monto cambia, el sistema pide comentario para dejar trazabilidad.",
        steps: [
          "Selecciona el gasto pendiente.",
          "Cambia la opcion a Monto diferente.",
          "Escribe el monto confirmado real.",
          "Completa el comentario explicando la diferencia.",
          "Pulsa Confirmar Gasto.",
        ],
      },
      {
        id: "confirm-expense-history",
        title: "Revisar el historial personal de gastos",
        screenArea: "Historial",
        audience: "all",
        steps: [
          "Abre la pestana Historial.",
          "Usa filtros por tipo, estado o buscador si lo necesitas.",
          "Revisa monto, estado, fecha y comentario de confirmacion.",
          "Si eres operador, veras sobre todo tus registros y tus confirmaciones.",
        ],
      },
    ],
  },
  {
    id: "stock",
    menuGroup: "Productos",
    menuButton: "Cargar Mercancia",
    screenTitle: "Pantalla de Carga de Mercancia",
    route: "/stock",
    access: "all",
    summary: "Permite sumar stock a un producto existente o crear un producto nuevo y cargarlo en el mismo paso.",
    screenAreas: ["Producto existente", "Producto nuevo", "Listado de productos"],
    actions: [
      {
        id: "stock-existing",
        title: "Cargar stock a un producto existente",
        screenArea: "Producto existente",
        audience: "all",
        steps: [
          "Entra en Cargar Mercancia.",
          "Deja seleccionado el modo de producto existente.",
          "Busca y selecciona el producto en la lista.",
          "Completa cantidad, costo, fecha de vencimiento si corresponde y descripcion.",
          "Guarda la carga para sumar el stock.",
        ],
      },
      {
        id: "stock-new-product",
        title: "Crear un producto nuevo y cargarlo",
        screenArea: "Producto nuevo",
        audience: "all",
        steps: [
          "Cambia al modo de producto nuevo.",
          "Completa nombre, categoria y, si corresponde, codigo de barras o generacion automatica.",
          "Carga costo, cantidad y datos del ingreso.",
          "Guarda la operacion.",
          "El sistema creara el producto y dejara el primer stock registrado.",
        ],
      },
      {
        id: "stock-margins",
        title: "Ajustar margenes durante la carga",
        screenArea: "Producto nuevo o existente",
        audience: "admin",
        steps: [
          "Si eres administrador, revisa el margen por categoria antes de guardar.",
          "Cuando haga falta, activa margen propio para un producto nuevo o ajusta el margen visible.",
          "Confirma el precio de venta que muestra la vista previa.",
          "Guarda la carga solo cuando costo, margen y precio esperado coincidan.",
        ],
      },
    ],
  },
  {
    id: "supply-receiving",
    menuGroup: "Productos",
    menuButton: "Recibir Mercancia",
    screenTitle: "Pantalla de Recepcion de Mercancia",
    route: "/supplies/receiving",
    access: "all",
    summary: "Se usa para recibir un pedido pendiente, cargar factura, informar faltantes y cerrar la recepcion.",
    screenAreas: ["Pedidos pendientes", "Recepcion", "Factura", "Impresion"],
    actions: [
      {
        id: "supply-receiving-select",
        title: "Elegir un pedido para recibir",
        screenArea: "Pedidos pendientes",
        audience: "all",
        steps: [
          "Entra en Recibir Mercancia.",
          "Revisa la lista de pedidos pendientes.",
          "Selecciona el pedido correcto por proveedor, fecha o total esperado.",
          "Confirma que los productos mostrados coincidan con la entrega fisica.",
        ],
      },
      {
        id: "supply-receiving-items",
        title: "Registrar faltantes y vencimientos",
        screenArea: "Recepcion",
        audience: "all",
        steps: [
          "Para cada producto, deja la cantidad faltante en cero si llego completo.",
          "Si faltaron unidades, escribe solo la cantidad faltante.",
          "Para lo recibido, completa la fecha de vencimiento cuando el sistema la pida.",
          "Si el importe no coincide, marca monto diferente y explica el motivo.",
        ],
      },
      {
        id: "supply-receiving-confirm",
        title: "Subir factura y confirmar la recepcion",
        screenArea: "Factura",
        audience: "all",
        steps: [
          "Carga una foto clara de la factura.",
          "Agrega un comentario si el monto pago fue distinto.",
          "Revisa que no quede ningun error de validacion.",
          "Confirma la recepcion del pedido.",
          "Si necesitas papel, puedes imprimir el listado del pedido antes o despues.",
        ],
      },
    ],
  },
  {
    id: "reports",
    menuGroup: "Administrativo",
    menuButton: "Balance",
    screenTitle: "Pantalla de Balance",
    route: "/balance",
    access: "admin",
    summary: "Concentra la lectura administrativa del negocio: jornadas, gastos, mercancia, ventas, caja y cuentas.",
    screenAreas: ["Jornadas", "Gastos", "Mercancia", "Ventas", "Caja", "Cuentas"],
    actions: [
      {
        id: "reports-workdays",
        title: "Revisar jornadas por dia, semana o mes",
        screenArea: "Jornadas",
        audience: "admin",
        steps: [
          "Entra en Balance y abre la pestana Jornadas.",
          "Elige Diario, Semanal o Mensual segun el periodo que quieras ver.",
          "Revisa cantidad de jornadas, operadores y total vendido.",
          "Abre una fila o grupo cuando necesites ver el detalle de un operador o una jornada.",
        ],
      },
      {
        id: "reports-operations",
        title: "Revisar gastos, mercancia y ventas del periodo",
        screenArea: "Gastos, Mercancia y Ventas",
        audience: "admin",
        steps: [
          "Cambia entre las pestanas Gastos, Mercancia y Ventas.",
          "En cada una revisa totales, listados y notas del sistema.",
          "Usa estas vistas para comparar movimientos reales del negocio.",
          "Si un numero llama la atencion, sigue luego con Jornadas o Transacciones.",
        ],
      },
      {
        id: "reports-cash",
        title: "Entrar al detalle de caja de una jornada",
        screenArea: "Caja",
        audience: "admin",
        steps: [
          "Abre la pestana Caja.",
          "Selecciona la jornada que quieras auditar.",
          "Revisa ventas, gastos, mercancia recibida y diferencia de cierre.",
          "Si hace falta mas detalle, usa el acceso a la jornada completa o cambia a otras pestanas relacionadas.",
        ],
      },
      {
        id: "reports-accounts",
        title: "Revisar cuentas financieras",
        screenArea: "Cuentas",
        audience: "admin",
        steps: [
          "Abre la pestana Cuentas.",
          "Revisa saldos, nombre de cuenta y movimientos asociados.",
          "Usa esta vista para entender de donde entra y sale el dinero.",
          "Si quieres el detalle linea por linea, continua luego en Transacciones.",
        ],
      },
    ],
  },
  {
    id: "finances",
    menuGroup: "Administrativo",
    menuButton: "Finanzas",
    screenTitle: "Pantalla de Finanzas",
    route: "/finances",
    access: "admin",
    summary: "Se usa para configurar margenes, formas de pago y el tratamiento del IVA.",
    screenAreas: ["Precios", "Metodos de pago", "Impuesto"],
    actions: [
      {
        id: "finances-category-margin",
        title: "Cambiar margen por categoria",
        screenArea: "Precios",
        audience: "admin",
        steps: [
          "Entra en Finanzas y abre la pestana Precios.",
          "Busca el bloque Margenes por categoria.",
          "Selecciona la categoria que quieres ajustar.",
          "Escribe el porcentaje nuevo y pulsa Guardar margen.",
          "Revisa el historial si necesitas confirmar el ultimo cambio.",
        ],
      },
      {
        id: "finances-product-override",
        title: "Crear o quitar un margen especial por producto",
        screenArea: "Precios",
        audience: "admin",
        steps: [
          "Dentro de Precios, busca Margen por producto.",
          "Selecciona el producto.",
          "Si quieres un valor propio, escribe el porcentaje y pulsa Guardar override.",
          "Si quieres volver al margen de categoria, pulsa Quitar override.",
          "Verifica el historial del producto para dejar trazabilidad.",
        ],
      },
      {
        id: "finances-payments",
        title: "Configurar descuentos o recargos por metodo de pago",
        screenArea: "Metodos de pago",
        audience: "admin",
        steps: [
          "Abre la pestana Metodos de pago.",
          "Elige el medio que quieres ajustar.",
          "Carga descuento, recargo o ambos segun la politica del negocio.",
          "Guarda cada metodo que modifiques.",
          "Prueba luego una venta para confirmar que el total final se vea como esperas.",
        ],
      },
      {
        id: "finances-tax",
        title: "Configurar el IVA",
        screenArea: "Impuesto",
        audience: "admin",
        steps: [
          "Entra en la pestana Impuesto.",
          "Escribe el porcentaje de IVA correcto.",
          "Elige si el sistema solo lo muestra o si lo suma al total final.",
          "Pulsa Guardar impuesto.",
          "Valida el comportamiento con una venta de prueba si hiciste cambios grandes.",
        ],
      },
    ],
  },
  {
    id: "transactions",
    menuGroup: "Administrativo",
    menuButton: "Transacciones",
    screenTitle: "Pantalla de Transacciones",
    route: "/transactions",
    access: "admin",
    summary: "Es una vista de solo lectura para seguir entradas y salidas de dinero por cuenta, tipo y modulo.",
    screenAreas: ["Cuentas", "Filtros", "Listado"],
    actions: [
      {
        id: "transactions-filter",
        title: "Filtrar movimientos para encontrar algo puntual",
        screenArea: "Filtros",
        audience: "admin",
        steps: [
          "Entra en Transacciones.",
          "Primero elige la cuenta o deja Todas.",
          "Luego filtra por Entrada/Salida o por tipo.",
          "Usa el buscador para titulo, modulo, referencia o actor.",
          "Lee los totales visibles de ingresos y egresos en la parte superior.",
        ],
      },
      {
        id: "transactions-read",
        title: "Leer el detalle de una transaccion",
        screenArea: "Listado",
        audience: "admin",
        steps: [
          "Busca la fila del movimiento que te interesa.",
          "Lee la fecha, cuenta, modulo y referencia.",
          "Mira si el importe esta marcado como entrada o salida.",
          "Revisa la descripcion completa y el actor relacionado.",
          "Si la transaccion es solo informativa, el listado tambien lo indica.",
        ],
      },
    ],
  },
  {
    id: "notifications",
    menuGroup: "Administrativo",
    menuButton: "Notificaciones",
    screenTitle: "Pantalla de Notificaciones",
    route: "/notifications",
    access: "admin",
    summary: "Permite revisar alertas, configurar tiempos y crear avisos manuales cuando haga falta.",
    screenAreas: ["Listado", "Requieren accion", "Vencimientos y fijas", "Duraciones", "Stock minimo", "Crear"],
    actions: [
      {
        id: "notifications-list",
        title: "Revisar el listado general de alertas",
        screenArea: "Listado",
        audience: "admin",
        steps: [
          "Entra en Notificaciones y deja activa la pestana Listado.",
          "Usa los filtros por texto, tipo, estado o fechas si la lista es grande.",
          "Haz clic en una alerta para ver el detalle completo.",
          "Desde el panel lateral puedes entender mejor referencia, vencimiento y accion.",
        ],
      },
      {
        id: "notifications-state",
        title: "Marcar una notificacion como recibida, deshabilitada o activa",
        screenArea: "Listado o detalle",
        audience: "admin",
        steps: [
          "Selecciona la notificacion que quieres actualizar.",
          "En el detalle usa el boton que corresponda: Marcar recibida, Deshabilitar o Reactivar.",
          "Confirma el mensaje del sistema.",
          "Revisa que el estado visible haya cambiado.",
        ],
      },
      {
        id: "notifications-action",
        title: "Ver solo las que requieren accion",
        screenArea: "Requieren accion",
        audience: "admin",
        steps: [
          "Abre la pestana Requieren accion.",
          "Revisa primero las mas nuevas o las que esten vencidas.",
          "Usa esta vista cuando necesites resolver pendientes rapidamente.",
        ],
      },
      {
        id: "notifications-duration",
        title: "Cambiar dias de aviso o duracion",
        screenArea: "Duraciones",
        audience: "admin",
        steps: [
          "Abre la pestana Duraciones.",
          "Selecciona el tipo de notificacion que quieres ajustar.",
          "Cambia dias de anticipo o dias de duracion.",
          "Guarda la configuracion.",
          "Repite el proceso para cada tipo que necesites ajustar.",
        ],
      },
      {
        id: "notifications-stock-threshold",
        title: "Configurar stock minimo por categoria o producto",
        screenArea: "Stock minimo",
        audience: "admin",
        steps: [
          "Entra en Stock minimo.",
          "Cambia primero los minimos por categoria si quieres una regla general.",
          "Despues usa minimos por producto solo para excepciones.",
          "Guarda cada cambio y verifica los overrides activos.",
        ],
      },
      {
        id: "notifications-create",
        title: "Crear una notificacion manual",
        screenArea: "Crear",
        audience: "admin",
        steps: [
          "Abre la pestana Crear.",
          "Elige si sera manual con accion, con vencimiento o fija.",
          "Completa titulo y descripcion.",
          "Si hace falta, agrega fecha de vencimiento o categoria.",
          "Pulsa Crear notificacion.",
        ],
      },
    ],
  },
  {
    id: "workdays",
    menuGroup: "Administrativo",
    menuButton: "Jornadas",
    screenTitle: "Pantalla de Jornadas",
    route: "/workdays",
    access: "admin",
    summary: "Muestra el historial de jornadas y el detalle de ventas de cada una.",
    screenAreas: ["Tabla de jornadas", "Detalle de jornada"],
    actions: [
      {
        id: "workdays-search",
        title: "Buscar una jornada",
        screenArea: "Tabla de jornadas",
        audience: "admin",
        steps: [
          "Entra en Jornadas.",
          "Usa filtros por ID, operador o fechas.",
          "Si necesitas otro orden, cambia la columna de ordenamiento.",
          "Haz clic en la jornada correcta para ver el detalle.",
        ],
      },
      {
        id: "workdays-detail",
        title: "Ver el detalle y las ventas de una jornada",
        screenArea: "Detalle de jornada",
        audience: "admin",
        steps: [
          "Selecciona una jornada desde la tabla.",
          "Revisa operador, inicio, cierre, duracion y total.",
          "Baja al bloque de ventas de esa jornada.",
          "Expande una venta cuando necesites ver mas informacion.",
        ],
      },
    ],
  },
  {
    id: "expenses-admin",
    menuGroup: "Administrativo",
    menuButton: "Gastos",
    screenTitle: "Pantalla completa de Gastos",
    route: "/expenses",
    access: "admin",
    summary: "La vista administrativa permite registrar gastos, confirmar pendientes y revisar historial.",
    screenAreas: ["Registrar gasto", "Confirmar Gasto", "Historial"],
    actions: [
      {
        id: "expenses-admin-create",
        title: "Registrar un gasto",
        screenArea: "Registrar gasto",
        audience: "admin",
        steps: [
          "Entra en Gastos y abre Registrar gasto.",
          "Elige si el gasto es imprevisto o programado.",
          "Escribe descripcion y monto.",
          "Carga la factura y, si aplica, la foto del imprevisto.",
          "Guarda el gasto para dejarlo pendiente de confirmacion.",
        ],
      },
      {
        id: "expenses-admin-confirm",
        title: "Confirmar un gasto pendiente",
        screenArea: "Confirmar Gasto",
        audience: "admin",
        steps: [
          "Abre Confirmar Gasto.",
          "Selecciona el gasto pendiente.",
          "Confirma el monto asignado o informa uno diferente.",
          "Si cambias el monto, deja comentario.",
          "Pulsa Confirmar Gasto.",
        ],
      },
      {
        id: "expenses-admin-history",
        title: "Revisar el historial de gastos",
        screenArea: "Historial",
        audience: "admin",
        steps: [
          "Abre Historial.",
          "Filtra por tipo, estado o texto si hace falta.",
          "Revisa total confirmado visible, fechas y responsables.",
          "Usa esta vista para seguimiento y cierre administrativo.",
        ],
      },
    ],
  },
  {
    id: "supply-orders",
    menuGroup: "Administrativo",
    menuButton: "Pedido Mercancia",
    screenTitle: "Pantalla de Pedidos de Mercancia",
    route: "/supplies/orders",
    access: "admin",
    summary: "Permite crear pedidos esperados, editarlos mientras sigan pendientes y reutilizar pedidos anteriores.",
    screenAreas: ["Nuevo pedido", "Pedidos cargados", "Catalogo y productos del pedido"],
    actions: [
      {
        id: "supply-orders-create",
        title: "Crear un pedido esperado",
        screenArea: "Nuevo pedido",
        audience: "admin",
        steps: [
          "Entra en Pedido Mercancia.",
          "Completa proveedor, descripcion y total esperado.",
          "Agrega productos desde el catalogo o crea uno nuevo si todavia no existe.",
          "Revisa cantidades pedidas.",
          "Pulsa Guardar pedido.",
        ],
      },
      {
        id: "supply-orders-edit",
        title: "Editar un pedido que sigue pendiente",
        screenArea: "Pedidos cargados",
        audience: "admin",
        steps: [
          "Abre la pestana Pedidos cargados.",
          "Busca un pedido con estado pendiente.",
          "Pulsa Editar para cargarlo en el formulario.",
          "Corrige proveedor, items o total esperado.",
          "Guarda los cambios.",
        ],
      },
      {
        id: "supply-orders-clone",
        title: "Volver a pedir productos usando un pedido anterior",
        screenArea: "Pedidos cargados",
        audience: "admin",
        steps: [
          "Busca un pedido parecido al que quieres repetir.",
          "Usa la opcion de cargar nuevamente o clonar.",
          "Revisa los productos que se copiaron al formulario.",
          "Ajusta cantidades si hace falta.",
          "Guarda el nuevo pedido.",
        ],
      },
      {
        id: "supply-orders-cancel",
        title: "Cancelar un pedido pendiente",
        screenArea: "Pedidos cargados",
        audience: "admin",
        steps: [
          "Ubica el pedido pendiente que ya no debes recibir.",
          "Pulsa la opcion de cancelar.",
          "Confirma la accion.",
          "Verifica que ya no figure como pendiente.",
        ],
      },
    ],
  },
  {
    id: "products-admin",
    menuGroup: "Administrativo",
    menuButton: "Productos",
    screenTitle: "Pantalla de Productos",
    route: "/products/new",
    access: "all",
    summary: "Sirve para crear, modificar, buscar y eliminar productos. El administrador tiene control total.",
    screenAreas: ["Formulario", "Listado", "Imagen", "Margenes"],
    actions: [
      {
        id: "products-create",
        title: "Crear un producto",
        screenArea: "Formulario",
        audience: "all",
        steps: [
          "Entra en Productos.",
          "Completa nombre, categoria, codigo de barras y precio de costo.",
          "Si usas imagen, cargala antes de confirmar.",
          "Revisa el precio de venta sugerido si tu perfil lo muestra.",
          "Pulsa Confirmar.",
        ],
      },
      {
        id: "products-edit",
        title: "Modificar un producto",
        screenArea: "Listado y Formulario",
        audience: "all",
        steps: [
          "Busca el producto en el listado.",
          "Selecciona el producto para cargarlo en el formulario.",
          "Corrige los datos necesarios.",
          "Pulsa Modificar.",
          "Verifica el mensaje de exito.",
        ],
      },
      {
        id: "products-delete",
        title: "Eliminar un producto",
        screenArea: "Formulario",
        audience: "all",
        note: "El administrador elimina directamente. El operador envia una solicitud al administrador.",
        steps: [
          "Selecciona el producto que quieres quitar.",
          "Pulsa Eliminar.",
          "Confirma la accion que te proponga el sistema.",
          "Espera el resultado segun tu perfil.",
        ],
      },
      {
        id: "products-search",
        title: "Buscar un producto en la lista",
        screenArea: "Listado",
        audience: "all",
        steps: [
          "Usa filtros por nombre, categoria, precio, stock o fecha.",
          "Ordena la tabla si hace falta.",
          "Cuando encuentres el producto, haz clic para cargarlo en el formulario.",
        ],
      },
    ],
  },
  {
    id: "approve-requests",
    menuGroup: "Administrativo",
    menuButton: "Aprobar Solicitudes",
    screenTitle: "Pantalla de Aprobacion de Solicitudes",
    route: "/requests/approvals",
    access: "admin",
    summary: "Permite revisar solicitudes pendientes, aprobar o rechazar, y convertir pedidos de mercancia en pedidos a proveedor.",
    screenAreas: ["Solicitudes pendientes", "Historial de solicitudes", "Generacion de pedido proveedor"],
    actions: [
      {
        id: "approve-requests-review",
        title: "Revisar una solicitud pendiente",
        screenArea: "Solicitudes pendientes",
        audience: "admin",
        steps: [
          "Entra en Aprobar Solicitudes.",
          "Selecciona una solicitud pendiente.",
          "Lee tipo, descripcion, usuario y fecha.",
          "Si hace falta, escribe un comentario de revision antes de decidir.",
        ],
      },
      {
        id: "approve-requests-permissions",
        title: "Aprobar o rechazar una solicitud de permisos",
        screenArea: "Solicitudes pendientes",
        audience: "admin",
        steps: [
          "Selecciona una solicitud de permisos.",
          "Escribe la respuesta o justificacion.",
          "Pulsa Aprobar o Rechazar.",
          "Comprueba que pase al historial con el estado correcto.",
        ],
      },
      {
        id: "approve-requests-merchandise",
        title: "Generar un pedido a proveedor desde una solicitud de mercancia",
        screenArea: "Generacion de pedido proveedor",
        audience: "admin",
        steps: [
          "Selecciona una solicitud de mercancia.",
          "Completa proveedor, mensaje para proveedor y monto esperado.",
          "Revisa el comentario de revision si quieres dejar contexto.",
          "Pulsa Generar.",
          "La solicitud quedara aprobada y se creara el pedido a proveedor.",
        ],
      },
      {
        id: "approve-requests-history",
        title: "Revisar el historial de solicitudes resueltas",
        screenArea: "Historial de solicitudes",
        audience: "admin",
        steps: [
          "Abre el bloque o tarjeta de Historial.",
          "Filtra por estado o por tipo si hace falta.",
          "Selecciona una solicitud para revisar comentario, fecha y quien la resolvio.",
        ],
      },
    ],
  },
  {
    id: "users",
    menuGroup: "Administrativo",
    menuButton: "Usuarios",
    screenTitle: "Pantalla de Usuarios",
    route: "/users",
    access: "admin",
    summary: "Permite crear, modificar, buscar y eliminar usuarios del sistema.",
    screenAreas: ["Formulario", "Listado", "Filtros"],
    actions: [
      {
        id: "users-create",
        title: "Crear un usuario",
        screenArea: "Formulario",
        audience: "admin",
        steps: [
          "Entra en Usuarios.",
          "Completa nombre, correo, usuario, clave y horario.",
          "Pulsa Guardar o Crear segun la vista.",
          "Revisa el mensaje de confirmacion.",
        ],
      },
      {
        id: "users-edit",
        title: "Modificar un usuario",
        screenArea: "Listado y Formulario",
        audience: "admin",
        steps: [
          "Selecciona un usuario del listado.",
          "Edita los datos necesarios en el formulario.",
          "Si no quieres cambiar la clave, deja ese campo vacio.",
          "Guarda la modificacion.",
        ],
      },
      {
        id: "users-delete",
        title: "Eliminar un usuario",
        screenArea: "Formulario",
        audience: "admin",
        steps: [
          "Selecciona el usuario a quitar.",
          "Pulsa el boton de eliminar.",
          "Confirma la accion cuando el sistema lo pregunte.",
          "Verifica que desaparezca del listado.",
        ],
      },
      {
        id: "users-search",
        title: "Buscar un usuario rapido",
        screenArea: "Filtros",
        audience: "admin",
        steps: [
          "Usa filtros por nombre, correo, usuario o fechas.",
          "Si la tabla es larga, cambia el orden para encontrarlo antes.",
          "Haz clic en la fila correcta para cargar el usuario en el formulario.",
        ],
      },
    ],
  },
  {
    id: "data",
    menuGroup: "Administrativo",
    menuButton: "Data",
    screenTitle: "Pantalla de Data",
    route: "/data",
    access: "admin",
    summary: "Es la pantalla mas sensible. Se usa para manejar bases de datos, cambiar la activa y limpiarla.",
    screenAreas: ["Acceso admin", "Crear nueva base", "Bases disponibles", "Limpiar base activa"],
    actions: [
      {
        id: "data-password",
        title: "Ingresar la clave administrativa",
        screenArea: "Acceso admin",
        audience: "admin",
        steps: [
          "Entra en Data.",
          "Escribe la clave del usuario administrador.",
          "No sigas si no estas seguro de la accion que vas a hacer.",
        ],
      },
      {
        id: "data-create-store",
        title: "Crear una nueva base",
        screenArea: "Crear nueva base",
        audience: "admin",
        note: "Hazlo solo cuando realmente necesites una base separada.",
        steps: [
          "Escribe un nombre simple para la nueva base.",
          "Pulsa Crear base.",
          "Confirma la ventana de seguridad.",
          "Espera el mensaje final y revisa que aparezca en Bases disponibles.",
        ],
      },
      {
        id: "data-switch-store",
        title: "Cambiar la base activa",
        screenArea: "Bases disponibles",
        audience: "admin",
        steps: [
          "Busca la base que quieres usar.",
          "Verifica bien nombre e ID antes de cambiar.",
          "Pulsa Usar esta base.",
          "Confirma la accion.",
          "Comprueba que ahora figure como Base activa.",
        ],
      },
      {
        id: "data-reset-store",
        title: "Limpiar la base activa",
        screenArea: "Limpiar base activa",
        audience: "admin",
        note: "Esta accion elimina informacion de la base activa. Debe hacerse con mucho cuidado.",
        steps: [
          "Confirma primero que estas parado en la base correcta.",
          "Pulsa Limpiar base activa.",
          "Acepta la confirmacion solo si estas totalmente seguro.",
          "Espera el mensaje final con fecha y hora.",
        ],
      },
    ],
  },
  {
    id: "licenses",
    menuGroup: "Administrativo",
    menuButton: "Permisos/Licencias",
    screenTitle: "Pantalla de Permisos y Licencias",
    route: "/licenses",
    access: "admin",
    summary: "Permite registrar permisos, controlar vencimientos y cargar renovaciones o nuevas expediciones.",
    screenAreas: ["Formulario", "Listado", "Alta o renovacion"],
    actions: [
      {
        id: "licenses-create",
        title: "Crear un permiso o licencia",
        screenArea: "Formulario",
        audience: "admin",
        steps: [
          "Entra en Permisos/Licencias.",
          "Completa nombre y descripcion.",
          "Si corresponde, agrega categoria, fechas y datos de contacto.",
          "Guarda el registro.",
          "Verifica que aparezca en el listado.",
        ],
      },
      {
        id: "licenses-edit",
        title: "Modificar un permiso existente",
        screenArea: "Formulario y Listado",
        audience: "admin",
        steps: [
          "Selecciona una licencia del listado.",
          "Corrige los datos necesarios en el formulario.",
          "Guarda la actualizacion.",
          "Revisa el mensaje de confirmacion.",
        ],
      },
      {
        id: "licenses-issuance",
        title: "Registrar una nueva alta, expedicion o renovacion",
        screenArea: "Alta o renovacion",
        audience: "admin",
        steps: [
          "Selecciona la licencia que vas a renovar o actualizar.",
          "Completa fecha de expedicion y fecha de vencimiento.",
          "Si hace falta, agrega notas.",
          "Guarda el alta.",
          "Verifica que el historial y las fechas de la licencia queden actualizados.",
        ],
      },
      {
        id: "licenses-filter",
        title: "Filtrar por estado o categoria",
        screenArea: "Listado",
        audience: "admin",
        steps: [
          "Usa el buscador si conoces parte del nombre o descripcion.",
          "Filtra por estado: activa, vencida o pendiente por renovar.",
          "Filtra por categoria si necesitas revisar solo un grupo.",
          "Selecciona la fila correcta para ver o editar el detalle.",
        ],
      },
    ],
  },
];
